FROM ubuntu
RUN apt-get update --fix-missing \
    && apt-get -y install openssh-server \
    && service ssh start \
    && apt-get -y install wget \
    && wget https://cdn.jsdelivr.net/gh/drkoubst/warehouse/docker-ssh/autossh.sh \
    && wget https://cdn.jsdelivr.net/gh/drkoubst/warehouse/docker-ssh/ssh_start.sh \
    && sed -i 's/\r//' autossh.sh \
    && chmod +x autossh.sh \
    && /bin/bash autossh.sh \
    && apt install -y python3 python3-pip
ADD . /
CMD bash ssh_start.sh
EXPOSE 22
EXPOSE 8888